#!/bin/bash
# Ruby front-end for your compiler.
# You are free to change the language used for this script,
# but do *not* change its name.

if [ $# -eq 0 ]
  then
    echo "No arguments supplied, please specify filepath as first argument"
    exit 1
fi

./gradlew run --console=plain --args="$1"
# with some arguments
# puts "TODO: setup this script to call your WACC compiler"
