#!/bin/bash
# Ruby front-end for your compiler.
# You are free to change the language used for this script,
# but do *not* change its name.

gradle run
# with some arguments
# puts "TODO: setup this script to call your WACC compiler"
