/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package wacc_05

import antlr.BasicLexer
import antlr.BasicParser
import org.antlr.v4.runtime.*
import java.io.File

fun main(args:Array<String>) {
//    App.runCompiler(args)
}

object App {

    @JvmStatic
    fun runCompiler(filePath: String): Int{

        println("Welcome to WACC: Please enter your input below")
        println("Remember to click enter at the end of input in this temporary solution")

        val inputStream = File(filePath).inputStream()
        val input = CharStreams.fromStream(inputStream)

        val lexer = BasicLexer(input)
        val errorListener = ErrorListener()
        lexer.removeErrorListeners()   // remove default ConsoleErrorListener
        lexer.addErrorListener(errorListener)

        val tokens = CommonTokenStream(lexer)
        val parser = BasicParser(tokens)
        val tree = parser.prog()
        println(tree.toStringTree(parser))
        println("FINISHED")
        return(0)
    }

}